name: Release Build

on:
  push:
    tags:
      - "v*" 
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g., 1.0.0)"
        required: true
        default: "0.0.1-dev"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    # 添加权限声明
    permissions:
      contents: write  # 关键权限修复
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取所有历史记录和标签

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Create ZIP archive
        run: |
          # 使用时间戳创建唯一文件名
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          zip -r build-$TIMESTAMP.zip dist/*
          echo "ZIP_FILE=build-$TIMESTAMP.zip" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1  # 回退到更稳定的版本
        with:
          tag_name: v${{ github.event.inputs.version || github.ref_name }}
          name: Release v${{ github.event.inputs.version || github.ref_name }}
          files: ${{ env.ZIP_FILE }}
          generate_release_notes: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
