name: Release Build

on:
  push:
    tags:
      - "v*" 
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g., 1.0.0)"
        required: true
        default: "0.0.1-dev"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Create ZIP archive
        run: zip -r build-${{ github.run_id }}.zip dist/*

      - name: Create Release
        # 使用更稳定的 release-action 替代
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.event.inputs.version || github.ref_name }}
          name: Release v${{ github.event.inputs.version || github.ref_name }}
          artifacts: "build-*.zip" # 上传压缩包
          generateReleaseNotes: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
